server:
  port: 9999
springdoc:
  api-docs:
    path: /open-api
    enabled: ${openapi.enabled}
  show-login-endpoint: true
spring:
  liquibase:
    driver-class-name: org.postgresql.Driver
    change-log: classpath:/db/changelog.yaml
    url: ${jdbc.db.url}
    default-schema: public
    user: ${jdbc.db.username}
    password: ${jdbc.db.password}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${jdbc.db.url}
    username: ${jdbc.db.username}
    password: ${jdbc.db.password}
  data:
    rest:
      detection-strategy: annotated
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
        hibernate:
            jdbc:
                time_zone: UTC
    open-in-view: false
  rabbitmq:
    addresses: ${rabbitmq.connection-url}
  cloud:
    stream:
      rabbit:
        default:
          consumer:
            autoBindDlq: true
            republishToDlq: true
      bindings:
        StartedRepairOfPlan-out-0:
          destination: dashclever.repairmanagment.repairing.repair-started
        blockPlansModifications-in-0:
          destination: dashclever.repairmanagment.repairing.repair-started
          group: dashclever.repairmanagment.planning.block-plans-modification
        indicateOngoingRepairOfEstimate-in-0:
          destination: dashclever.repairmanagment.repairing.repair-started
          group: dashclever.repairmanagment.planning.indicate-ongoing-repair-of-estimate

logging:
  level:
    org:
      springframework:
        security: ${spring.security.logging}
