# Do not use in CI/CD
version: "3.9"

services:
  postgresql:
    image: postgres:15
    volumes:
      - app-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  app-db-volume:
