services:
  postgresql:
    image: postgres:15
    volumes:
      - dashclever-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dashclever
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      dashclever_default:
        ipv4_address: 10.5.0.6

volumes:
  dashclever-volume:

networks:
  dashclever_default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1