services:
  postgresql:
    image: postgres:15
    volumes:
      - dashclever-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dashclever
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - dashclever_default

volumes:
  dashclever-volume:
