# Do not use in CI/CD
version: "3.9"

services:
  postgresql:
    container_name: 'dashclever-postgresql'
    image: postgres:15
    volumes:
      - dashclever-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dashclever
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'dashclever-rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_USER: admin

volumes:
  dashclever-volume:
